In [1]:
import numpy as np

In [2]:
# Ones
np.ones([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
# zeros array
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
# randomization
np.random.random([3,])

array([0.38033047, 0.4693342 , 0.249395  ])

In [7]:
np.random.random([5, 3])

array([[0.1514925 , 0.77517227, 0.4619597 ],
       [0.13008827, 0.33683975, 0.20126459],
       [0.61919148, 0.35932269, 0.39302629],
       [0.73022341, 0.06324257, 0.96337005],
       [0.82313437, 0.73968089, 0.58643718]])

In [12]:
np.random.randn(3, 3)

array([[-1.47691118,  1.17897095,  0.9539733 ],
       [-0.74789156, -0.49722953, -0.77553666],
       [-0.81300386, -1.52399728, -0.95835382]])

In [13]:
np.random.rand(4, 3)

array([[0.94912085, 0.73720985, 0.7031303 ],
       [0.15409393, 0.02300346, 0.22849952],
       [0.24286871, 0.72759149, 0.99458066],
       [0.95159454, 0.92089818, 0.94530182]])

In [16]:
np.random.random([4, 1])

array([[0.04616688],
       [0.20579312],
       [0.77564337],
       [0.0576401 ]])

### Matrix properties and Operations

**Dimension of array**

In [17]:
x = np.array([3, 4])

In [18]:
x.shape

(2,)

In [19]:
y = np.array([[3, 4, 1], [8, 3, 4]])

In [20]:
y

array([[3, 4, 1],
       [8, 3, 4]])

In [21]:
y.shape

(2, 3)

**Transposition of matrix**

In [22]:
y.transpose()

array([[3, 8],
       [4, 3],
       [1, 4]])

In [23]:
z = y.transpose()

In [24]:
z.shape

(3, 2)

In [25]:
z

array([[3, 8],
       [4, 3],
       [1, 4]])

**Functions**

In [26]:
y = np.array([
    [3, 5, 1],
    [1, 3, 9]
])

In [27]:
y

array([[3, 5, 1],
       [1, 3, 9]])

In [31]:
z = y + 3

In [32]:
z

array([[ 6,  8,  4],
       [ 4,  6, 12]])

In [33]:
y * z

array([[ 18,  40,   4],
       [  4,  18, 108]])

We can multiply matrix using **multiply** Function

In [34]:
np.multiply(y, z)

array([[ 18,  40,   4],
       [  4,  18, 108]])

**Matrix vectoriel product**

To compute the vectoriel matrix multiplication, we use **matmul** function

In [36]:
x

array([3, 4])

In [37]:
y

array([[3, 5, 1],
       [1, 3, 9]])

In [38]:
np.matmul(x, y)

array([13, 27, 39])

**Exponential**

In [39]:
np.exp(x)

array([20.08553692, 54.59815003])

**Cosine of matrix**

In [40]:
np.cos(x)

array([-0.9899925 , -0.65364362])

**Tangente of matrix**

In [42]:
np.tan(x)

array([-0.14254654,  1.15782128])

**Hyperbolic tagente**

In [43]:
np.tanh(x)

array([0.99505475, 0.9993293 ])

In [44]:
np.random.random([3, 2])

array([[0.09991938, 0.32185213],
       [0.16797103, 0.7736962 ],
       [0.6334778 , 0.68631035]])

In [45]:
x + x

array([6, 8])

In [48]:
np.sum([x])

7

#### MIN, MAX AND NORM

In [49]:
x = np.array([23, 19, 1, 3, -2, 7, 9, 1])

In [50]:
x

array([23, 19,  1,  3, -2,  7,  9,  1])

**MIN**

In [52]:
np.min(x)   # Minimum of array

-2

**MAX**

In [53]:
np.max(x)    # Maximum of array

23

**NORM**

In [54]:
np.linalg.norm(x)   # Norm of matrix x --> np.sqrt((x1 ** 2 + x2 ** 2 + .... + xn ** 2))

32.17141588429082

**EXERCICE**
**NEURAL NETWORK FUNCTION**

 Here, we will write a function neural_network, which will apply a neural network operation with 2 inputs and 1 output and a given weight matrix.

Available Functions: You have access to the NumPy python library as np

Your function should take two arguments: inputs and weights, two NumPy arrays of shape and should return a NumPy array of shape , the output of the neural network. Do not forget the activation. 

In [57]:
x = np.random.random([2, 1])

In [58]:
x

array([[0.8012246 ],
       [0.21337056]])

In [59]:
x.shape

(2, 1)

In [61]:
z = np.matmul(x, x.transpose())

In [62]:
z

array([[0.64196086, 0.17095774],
       [0.17095774, 0.045527  ]])

In [63]:
z.shape

(2, 2)

In [66]:
y = x * x

In [67]:
y

array([[0.64196086],
       [0.045527  ]])

In [69]:
v = np.sum(y)

In [70]:
v

0.687487854015611

In [72]:
z = np.tanh(v)

In [73]:
z

0.5963657292961912

In [76]:
np.array([z]).shape

(1,)

In [97]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    try:
        compute_entries = (inputs * weights)  # to multiply the inputs values with theirs coresponding weights
        sum_entries = np.sum(compute_entries) # Addition of entries
        out = np.array([[np.tanh(sum_entries)]])
        return out
    except:
        raise NotImplementedError


In [98]:
inputs = np.array([[3], [1]])
weights = np.array([[0.4], [0.7]])

output = neural_network(inputs, weights)

In [99]:
output

array([[0.95623746]])

In [100]:
output.shape

(1, 1)

In [101]:
inputs.shape

(2, 1)

In [102]:
np.array([[1]]).shape

(1, 1)

In [114]:
np.vectorize?

In [105]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    try:
        if x <= y:
            return x * y
        else:
            return x / y
    except:
        raise NotImplementedError

In [115]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    try:
        vfunc =  np.vectorize(scalar_function)
        return vfunc(x, y)
    except:
        raise NotImplementedError



In [116]:
a = vector_function(3, 5)

In [117]:
a

array(15)